global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['prometheus:9090']
    metrics_path: 'metrics'
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node_exporter:9100']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8098']
  # - job_name: "tasmota"
  #   # metrics_path defaults to '/metrics'
  #   # scheme defaults to 'http'.
  #   static_configs:
  #       - targets: ["tasmota-power-2:8002"]

# Tasmota
  - job_name: "tasmota-1"
    static_configs:
      - targets: ["tasmota-power-1:8000"]

  - job_name: "tasmota-2"
    static_configs:
      - targets: ["tasmota-power-2:8000"]

  - job_name: "tasmota-3"
    static_configs:
      - targets: ["tasmota-power-3:8000"]

  - job_name: "tasmota-4"
    static_configs:
      - targets: ["tasmota-power-4:8000"]
